# Generated by Django 5.1.1 on 2024-09-28 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_shelterlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShelterLocation',
        ),
    ]
