# Generated by Django 5.1.1 on 2024-09-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_shelterlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('food', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('water', models.IntegerField()),
                ('electricity', models.IntegerField()),
                ('first_aid', models.IntegerField()),
            ],
        ),
    ]
