# Generated by Django 5.1.1 on 2024-09-29 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_unverifiedshelter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnverifiedShelter',
        ),
    ]
