# Generated by Django 5.1.1 on 2024-09-29 03:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_unverifiedshelter'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnverifiedShelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('total_capacity', models.IntegerField(default=0)),
                ('available_beds', models.IntegerField()),
                ('available_food', models.BooleanField()),
                ('available_medical_supplies', models.BooleanField()),
                ('electricity', models.BooleanField()),
                ('water', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('latitude', 'longitude')},
            },
        ),
    ]
